#!/bin/bash -e

export PATH=$PATH:/usr/local/bin

if [ $1 == "test" ]
then
    carthage update --platform iOS
    xcodebuild test -scheme Networking -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 6'
fi
if [ $1 == "build" ]
then
    rm -rf Carthage/Build/iOS
    carthage build --no-skip-current --platform iOS
fi
